name: somnio
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  somnio_repository:
    path: packages/somnio_repository
  somnio_service:
    path: packages/somnio_service

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  build_runner: ^2.1.10
  freezed: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/